project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "./WonderLab.Override.I18n/Languages"
preserve_hierarchy: true

files:
  - source: "en-US.xaml"
    translation: "%locale%.xaml"