project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "./WonderLab.Override.I18n/Languages"
preserve_hierarchy: true

files:
  - source: "zh-Hans.xaml"
    translation: "%file_name%.xaml"